### PR TITLE
[WIP] Spanish Translation

### PR DESCRIPTION
**Pull request by Dokman**
Is a work in progress in a few days i'll have it at 100%

### CODE REVIEW

**Comment by rubensworks** [comment]
Great! Just let me know once it's finished.

**Comment by Dokman** [comment]
@rubensworks In 1 or 2 days more i will finish it and translate it into catalan too

**Comment by rubensworks** [comment]
Ok awesome. Could you squash your commits in here once you are finished? I prefer to have changes to things grouped in one nice commit :)

**Comment by Dokman** [comment]
yes but how i do it?

**Comment by rubensworks** [comment]
http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
It might not be a bad idea to try this out in a separate test repo first, because you can break stuff with this when not done properly.

**Comment by Dokman** [comment]
this is no? https://github.com/Dokman/EvilCraft/tree/Squashed
@rubensworks

**Comment by rubensworks** [comment]
Yes, that looks good! If I'm correct you can also somewhere change the first line of commit message to something like 'Create es_ES.lang'.

**Comment by Dokman** [comment]
yes ^^

**Comment by Dokman** [comment]
@rubensworks Sorry today i will not work i have personal troubles and i am little depressed
Sorry

**Comment by rubensworks** [comment]
No worries, there's no hurry.

**Pull request closed without merging**
